// <auto-generated />
using System;
using HobbyRadarAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HobbyRadarAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210917235851_CreateSampleUsers")]
    partial class CreateSampleUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HobbyRadarAPI.Models.Connection", b =>
                {
                    b.Property<string>("User1Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("User2Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("User1Id", "User2Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.ConnectionInvite", b =>
                {
                    b.Property<int>("ConnectionInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("bit");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionInviteId");

                    b.ToTable("ConnectionInvites");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.EventAttendance", b =>
                {
                    b.Property<int>("ScheduledEventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ScheduledEventId", "UserId");

                    b.ToTable("EventAttendances");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.HobbyTag", b =>
                {
                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("HobbyId", "TagId");

                    b.ToTable("HobbyTags");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.ScheduledEvent", b =>
                {
                    b.Property<int>("ScheduledEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduledEventId");

                    b.HasIndex("HobbyId");

                    b.ToTable("ScheduledEvents");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserZip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "fb7e4aa9-de58-4e19-bc7c-cedabc8d1054",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "986e22d3-c985-4ddd-9dec-b28d6a0b6fc3",
                            Email = "username.01@website.com",
                            EmailConfirmed = false,
                            FirstName = "Virgil",
                            LastName = "Nichols",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ee3aae5-23c4-4884-ba89-de4dbacdef0d",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username01",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "8baa663b-5422-4e0d-9d89-8d85eacb0e5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88cb3c8d-4ad4-422b-8c3d-f59dc2e4a167",
                            Email = "username.02@website.com",
                            EmailConfirmed = false,
                            FirstName = "Donald",
                            LastName = "Williams",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7bb0549d-82ac-4627-b374-c8b85c825a01",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username02",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "c7629af8-b837-4e6d-a0d5-156a88c2749d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9992278d-8326-4c00-b17b-17609735157c",
                            Email = "username.03@website.com",
                            EmailConfirmed = false,
                            FirstName = "Victor",
                            LastName = "English",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92db1fd5-d1bf-49da-80b5-01554fd0ecde",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username03",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "cd834580-5220-4fed-a923-fc03e1d3de14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ccfb7469-13c4-4b74-ac19-17dd220e6d28",
                            Email = "username.04@website.com",
                            EmailConfirmed = false,
                            FirstName = "Marilyn",
                            LastName = "Jensen",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e25cddd7-4e70-4aa1-9476-03de0a10c997",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username04",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "ad20d1ce-eb30-4ef1-82bb-3de9190cefcb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2508f43e-8d7c-4344-9dbf-50a980857b29",
                            Email = "username.05@website.com",
                            EmailConfirmed = false,
                            FirstName = "Joseph",
                            LastName = "Hensley",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10894e6c-73ac-46df-bd4b-35da3cf9b3b6",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username05",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "558de276-cdd7-4f80-b7a7-9471e579788f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf9093a3-5416-4a9b-b004-ae4fa85cc924",
                            Email = "username.06@website.com",
                            EmailConfirmed = false,
                            FirstName = "Joan",
                            LastName = "Nicholson",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7b73062-0b08-438b-83b4-3dedc719ae88",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username06",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "f079118a-23ea-4723-a979-27ae21dafbe1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4565a8d5-fae1-40bf-bc57-cc736f08e0bf",
                            Email = "username.07@website.com",
                            EmailConfirmed = false,
                            FirstName = "Jen",
                            LastName = "Hinton",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ecc6636-419c-4d82-a8e1-59a9e016ead7",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username07",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "3e6268e0-e090-4291-a610-8004347721dc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66cfe664-392d-4147-a0ab-64ddba38221e",
                            Email = "username.08@website.com",
                            EmailConfirmed = false,
                            FirstName = "Janet",
                            LastName = "Holloway",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46a7d898-4869-49fc-8d89-0347b2eaba2f",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username08",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "67b050e9-93d3-4539-a13b-dfbcf27361b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0507341b-aeed-4c60-bd05-b17147141012",
                            Email = "username.09@website.com",
                            EmailConfirmed = false,
                            FirstName = "Vince",
                            LastName = "McClain",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "90fb4b5a-e930-4681-9e7f-a98b6125f13c",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username09",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "1f22c979-726f-4962-b2b5-bf5e83cc13f1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33144246-7418-41d3-83bd-b91850754a1d",
                            Email = "username.10@website.com",
                            EmailConfirmed = false,
                            FirstName = "Rebbecca",
                            LastName = "Patton",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70d3cafc-fc2f-477c-bb6a-148ef325648e",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username10",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "8c0f6526-4964-4e75-82cc-dc7f5c662e5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e23dce04-9e37-4cb9-a253-3a4c2f98c411",
                            Email = "username.11@website.com",
                            EmailConfirmed = false,
                            FirstName = "Ann",
                            LastName = "McConnell",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e973e6c9-473b-49d3-a920-35a1863a6698",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username11",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "737dd08e-80c1-45bd-a2b9-98a5d324cd1a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bff9e36-6535-4a7d-afcd-e948cc28e7af",
                            Email = "username.12@website.com",
                            EmailConfirmed = false,
                            FirstName = "Brandy",
                            LastName = "Booth",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d4080658-d8de-45c6-ac31-3b35d565d23c",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username12",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "55367a6a-2505-4ce4-99cf-b77d55df3320",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad396600-4bce-4694-b59d-e14e421e8e37",
                            Email = "username.13@website.com",
                            EmailConfirmed = false,
                            FirstName = "Curtis",
                            LastName = "Allison",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2559cbc9-dbf6-4bd5-883d-5de7e4ebadcf",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username13",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "b4769c29-8598-480b-b5d3-698700864869",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a16884d-37c3-4fba-b6e5-546c6fdff086",
                            Email = "username.14@website.com",
                            EmailConfirmed = false,
                            FirstName = "Stan",
                            LastName = "Carr",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e8707fd-1d80-4f09-a9d8-4d5056e2c767",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username14",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "9adfe112-4c41-4022-a5fe-62a83e8fc299",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b91c097-dbc5-46d8-9467-95a530751244",
                            Email = "username.15@website.com",
                            EmailConfirmed = false,
                            FirstName = "Joe",
                            LastName = "Cowan",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07c95b55-ec56-43e6-8239-0dd49db188d5",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username15",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "406efbec-e351-4369-a812-d7a0df894b30",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f342db1d-0dff-4446-8fd3-f27235ba7a1e",
                            Email = "username.16@website.com",
                            EmailConfirmed = false,
                            FirstName = "Jenna",
                            LastName = "Farmer",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0094d1c9-6044-427a-90f7-66549a8dd2ae",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username16",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "4968a764-9310-40b7-b114-08ad4a191db5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ce85098-c91a-47d8-b3ea-6aa35414b28f",
                            Email = "username.17@website.com",
                            EmailConfirmed = false,
                            FirstName = "Cecelia",
                            LastName = "Rider",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c582d7e6-d5fa-4f27-8b94-bc937861d1c3",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username17",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "dbbd1a5a-1161-483e-a705-5cb5b640f239",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da843782-a693-4636-8b83-8a2f04a38d5e",
                            Email = "username.18@website.com",
                            EmailConfirmed = false,
                            FirstName = "Thelma",
                            LastName = "Daily",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "84735bad-46ed-485a-9e1f-7de529f99bf1",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username18",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "b455a890-08c6-4e6f-bfe7-30cc99cf2f72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05bb05a7-7409-4df2-8f1f-882b4d82cc44",
                            Email = "username.19@website.com",
                            EmailConfirmed = false,
                            FirstName = "Rudy",
                            LastName = "Sears",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb57f2e3-5eba-4466-81e0-0647030bb9b1",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username19",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "1f6fbbd3-5b86-4154-bd59-10901df0ad81",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "525fed36-cbd2-4c30-ba7d-b1643291e1c1",
                            Email = "username.20@website.com",
                            EmailConfirmed = false,
                            FirstName = "Kristen",
                            LastName = "Booker",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00ae55df-09c1-4372-b557-7a1706a7904e",
                            TwoFactorEnabled = false,
                            UserCity = "Milwaukee",
                            UserName = "username20",
                            UserState = "WI",
                            UserZip = "53172"
                        },
                        new
                        {
                            Id = "48ed259d-18c9-47fe-9e67-111dbc445fd4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65ae79cf-900d-4838-a531-b5b25572f28c",
                            Email = "username.21@website.com",
                            EmailConfirmed = false,
                            FirstName = "Greg",
                            LastName = "Haines",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e81b009d-a438-449c-bf0f-c0fe798afe0f",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username21",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "404e8d45-1b49-448a-be30-9ecc57b340af",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d220ff1-4f43-4f34-8ca1-2f3301ab2596",
                            Email = "username.22@website.com",
                            EmailConfirmed = false,
                            FirstName = "Roy",
                            LastName = "Shields",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "863171ce-bd82-4364-afd3-b6c75a6e2484",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username22",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "39dd92a6-b55d-4f0f-b614-76b15b550678",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7de199bb-cb20-464d-b5c4-de381de321c0",
                            Email = "username.23@website.com",
                            EmailConfirmed = false,
                            FirstName = "Pablo",
                            LastName = "Sanders",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74c31ce0-710d-4d1b-a8d2-1fcb6c89b1f4",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username23",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "90e68dbf-d08e-4b3a-bb44-642f44826249",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75143711-d03d-42be-823e-6012afdc9876",
                            Email = "username.24@website.com",
                            EmailConfirmed = false,
                            FirstName = "Bonita",
                            LastName = "Reese",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f96377b9-b8dd-4574-9f0d-57ff1d6b82e1",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username24",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "e741c863-683d-4a5b-aad9-7bec025a352b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7afae394-2792-403b-a2fe-53f9f62927de",
                            Email = "username.25@website.com",
                            EmailConfirmed = false,
                            FirstName = "Dolores",
                            LastName = "Wolfe",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "917cbfd8-26f5-4a78-899a-e027356fbf4a",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username25",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "728d5de5-a876-4ec3-ae28-f9bd5d54e504",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3efbf91b-5045-4abc-b422-472602ca6c02",
                            Email = "username.26@website.com",
                            EmailConfirmed = false,
                            FirstName = "Delia",
                            LastName = "Liu",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "800fe41d-0292-4284-aa80-7b13746fbc51",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username26",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "d6c218c0-a1f4-4ec4-a43a-ed23ba5f1088",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c952830e-2bf8-418d-b05d-2a682d12e819",
                            Email = "username.27@website.com",
                            EmailConfirmed = false,
                            FirstName = "Pedro",
                            LastName = "Anthony",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c003ee22-a171-478b-ba99-9ac4c66def73",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username27",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "35f1d1ab-7b0b-49f5-9d45-5d44ca8d2d4a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82f3cd6a-1f9b-457d-be6e-5ab65edecf26",
                            Email = "username.28@website.com",
                            EmailConfirmed = false,
                            FirstName = "Roman",
                            LastName = "Jackson",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8b06299-3cc1-49c2-bd2b-974b36894180",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username28",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "e47ff457-1df0-4275-9d6c-e76fe98fa961",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a5ed749-508f-4154-818d-d2e1bcfbfecf",
                            Email = "username.29@website.com",
                            EmailConfirmed = false,
                            FirstName = "Cory",
                            LastName = "Cunningham",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e81b478-2b51-4d2b-bab0-ac5eea13f213",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username29",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "a1abf5b1-34bd-46cd-ace4-7623fe26813b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "efa42e8e-179a-430e-b879-59729643ffdb",
                            Email = "username.30@website.com",
                            EmailConfirmed = false,
                            FirstName = "Rosemarie",
                            LastName = "McGuire",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5593f0a9-c2ec-4ba6-a895-39735ef7f003",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username30",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "6f57cdbe-e41f-4d6b-8e11-ebe076723861",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46fdaad9-75b5-4677-90f1-21805c1fe1d5",
                            Email = "username.31@website.com",
                            EmailConfirmed = false,
                            FirstName = "Frances",
                            LastName = "Cantu",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31a7f6b5-a55e-4836-837e-2388ee07872b",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username31",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "caacdd8d-c803-4680-aa29-fe0d99f67abb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d369e591-80d1-4d72-abcf-f48ef65ac238",
                            Email = "username.32@website.com",
                            EmailConfirmed = false,
                            FirstName = "Edward",
                            LastName = "Bradford",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4a7c992-f0e9-43f4-be0d-11a2a2348585",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username32",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "d957f266-695c-4e51-bb05-ddd4c78ab54b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bb9e5330-38d0-4f12-9f49-fb94d9a6fcca",
                            Email = "username.33@website.com",
                            EmailConfirmed = false,
                            FirstName = "Merle",
                            LastName = "Myers",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3888b9b9-9261-4407-928c-551c98ff99d7",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username33",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "977a193e-b63c-4b74-8c2c-13fac432a3ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54a4ce2c-3e2f-41f6-96ea-2706f425ea49",
                            Email = "username.34@website.com",
                            EmailConfirmed = false,
                            FirstName = "Gerald",
                            LastName = "Livingston",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33846984-727f-47ca-9992-53d5cebbb941",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username34",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "e303170d-4192-4733-b5a2-7eafea38e142",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "074025b6-008e-4484-bfc3-dcceaee44953",
                            Email = "username.35@website.com",
                            EmailConfirmed = false,
                            FirstName = "Deborah",
                            LastName = "Simon",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4dfa8518-24fa-4a85-8a6e-7494ad298f52",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username35",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "82c5f76c-51ee-4c0a-bc26-f96cac06b92b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0df47a0-72b6-4442-a785-f287a4daeea9",
                            Email = "username.36@website.com",
                            EmailConfirmed = false,
                            FirstName = "Neal",
                            LastName = "Thornton",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1ff325c-f7b8-4154-ad85-70a01c4a2cff",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username36",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "42d8c277-8adb-4479-9499-1f52b917b528",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab5428c1-e91a-48bf-92d1-22938d1cbe4f",
                            Email = "username.37@website.com",
                            EmailConfirmed = false,
                            FirstName = "Sandi",
                            LastName = "Norton",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09592ac3-1584-4ed8-91a4-e2e34fb1652c",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username37",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "e70b4e31-573d-4132-9867-4c0a7f7302ec",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82d40c49-7827-4ee7-bf39-376adb403dfa",
                            Email = "username.38@website.com",
                            EmailConfirmed = false,
                            FirstName = "Julian",
                            LastName = "Farley",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "304ad909-dc6a-49ce-ac8f-547b9dcf3f52",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username38",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "e5a62d42-8dde-4584-9107-19a825c9d241",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "06fc56e0-314a-4f55-ab56-46fb724dc804",
                            Email = "username.39@website.com",
                            EmailConfirmed = false,
                            FirstName = "Mercedes",
                            LastName = "Stafford",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cd76d1ac-ae58-400a-bcb0-f4c3cd6187a4",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username39",
                            UserState = "MN",
                            UserZip = "55403"
                        },
                        new
                        {
                            Id = "3047431e-a67a-47b7-8ff6-d524c3583be0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "471680db-7a08-4b71-b14a-40a1a81703fb",
                            Email = "username.40@website.com",
                            EmailConfirmed = false,
                            FirstName = "Rene",
                            LastName = "Gilmore",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEPdhpwoFO9D08m7ShJwltbFOOjVhj0t0iYEr2RBbzkCJScWiTkfnD0J2drhMZg1FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82720385-aff4-44ba-a8b0-0d2a441d560e",
                            TwoFactorEnabled = false,
                            UserCity = "Minneapolis",
                            UserName = "username40",
                            UserState = "MN",
                            UserZip = "55403"
                        });
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.UserAlert", b =>
                {
                    b.Property<int>("UserAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Dismissed")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserAlertId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAlerts");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.UserHobbyRating", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "HobbyId");

                    b.ToTable("UserHobbyRating");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "1b1e5957-c8a2-4bb3-b9e4-49235dfbd3dc",
                            ConcurrencyStamp = "e242c7af-f217-4b9c-b06d-81658ed76e6a",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "79012546-13c0-4fe7-9ad5-0a74a7945980",
                            ConcurrencyStamp = "ef747f7b-e12c-4b2b-b0f7-a12a834beeb1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.HobbyTag", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.Hobby", null)
                        .WithMany("HobbyTags")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.ScheduledEvent", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.Hobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.UserAlert", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HobbyRadarAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HobbyRadarAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HobbyRadarAPI.Models.Hobby", b =>
                {
                    b.Navigation("HobbyTags");
                });
#pragma warning restore 612, 618
        }
    }
}
